version: "2"
services:
  app:
    container_name: api-todos
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-todos
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
